name = "Prox Farmers"
author = "mel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0099ccfc3d254f87495d77802569ddc289bafbfe22046e132a4f440fb7d6db95"

[versions]
fabric = "0.16.10"
minecraft = "1.21"

[options]
acceptable-game-versions = []
datapack-folder = "./datapacks"
