name = "RM Craft"
author = "mel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b1b9939c4870fedbffe8bbdd4a36e59f587eaffb1a542e04db72936b12a2335"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
