name = "RM Craft"
author = "mel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf991fc44dbbc202a6a09927252d3187043a4d5221543c719589fdaa6ad653f4"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
datapack-folder = "./datapacks"
