name = "RM Craft"
author = "mel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "494c684b32f8d9a87af3d0375df51d0164a996e023fb82eb411578c60cedf665"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
