name = "RM Craft"
author = "mel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "685cce6a40200d710770b81aba7b8a6d6a913ece644c6a03348442376602e844"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
datapack-folder = "./datapacks"
