name = "RM Craft"
author = "mel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aeb0a19e567bc6d5022dc56cb5159cd9d18d84e9363f8327a5f5cdb3b6669f6f"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
datapack-folder = "./datapacks"
